services:
  - type: web
    name: gis-watermeter
    runtime: node
    plan: free
    region: singapore
    healthCheckPath: /health
    buildCommand: npm install --include=dev && npm run build:nest
    startCommand: npm run start:nest
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 24
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: CRON_SECRET
        generateValue: true
      - key: BASE_URL
        sync: false
