services:
  - type: web
    name: gis-watermeter
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
